# Generated by Django 4.2.30 on 2026-05-10 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_contentchunk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['order_num']},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order_num']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order_num']},
        ),
        migrations.AlterModelTable(
            name='chapter',
            table='curriculum_chapter',
        ),
        migrations.AlterModelTable(
            name='contentchunk',
            table='curriculum_content_chunk',
        ),
        migrations.AlterModelTable(
            name='lesson',
            table='curriculum_lesson',
        ),
        migrations.AlterModelTable(
            name='topic',
            table='curriculum_topic',
        ),
    ]
