# Generated by Django 4.2.30 on 2026-05-10 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_standardize_db_table_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={},
        ),
        migrations.AlterModelTable(
            name='chapter',
            table='chapters',
        ),
        migrations.AlterModelTable(
            name='contentchunk',
            table='content_chunks',
        ),
        migrations.AlterModelTable(
            name='lesson',
            table='lessons',
        ),
        migrations.AlterModelTable(
            name='topic',
            table='topics',
        ),
    ]
