# Generated by Django 4.2.30 on 2026-05-14 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0010_alter_subject_table_alter_subjectdocument_table_and_more'),
        ('curriculum', '0005_alter_chapter_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['order_num']},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order_num']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order_num']},
        ),
        migrations.AddField(
            model_name='chapter',
            name='chapter_number',
            field=models.CharField(blank=True, help_text="Số thứ tự (ví dụ: '1', 'I', 'A')", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='chapter_type',
            field=models.CharField(choices=[('CHAPTER', 'Chương'), ('THEME', 'Chủ đề')], default='CHAPTER', help_text='Loại cấp bậc: Chương hay Chủ đề', max_length=10),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_number',
            field=models.CharField(blank=True, help_text="Số bài (ví dụ: '1', '2', '3')", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='page_end',
            field=models.IntegerField(blank=True, help_text='Trang kết thúc (ước tính)', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='page_start',
            field=models.IntegerField(blank=True, help_text='Trang bắt đầu (in trên sách)', null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='order_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(help_text='Tên đầy đủ (ví dụ: Chương 1: Mệnh đề)', max_length=512),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, help_text='Tag [PAGE X-Y] hoặc nội dung tóm tắt', null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(help_text='Tên đầy đủ bài học', max_length=512),
        ),
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=models.TextField(blank=True, help_text='Nội dung lý thuyết tóm tắt', null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=512),
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tên phần (ví dụ: Giáo dục Kinh tế)', max_length=255)),
                ('order_num', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='subjects.subject')),
            ],
            options={
                'db_table': 'parts',
                'ordering': ['order_num'],
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='part',
            field=models.ForeignKey(blank=True, help_text='Phần/Khối chứa Chương này (nếu có)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapters', to='curriculum.part'),
        ),
    ]
