# Generated by Django 4.2.30 on 2026-05-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_add_part_and_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='ten_chu_de',
            field=models.CharField(blank=True, db_column='ten_chu_de', help_text='Tên Chủ đề - chỉ điền khi chapter_type=THEME (ví dụ: Vật lí nhiệt)', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='ten_chuong',
            field=models.CharField(blank=True, db_column='ten_chuong', help_text='Tên Chương - chỉ điền khi chapter_type=CHAPTER (ví dụ: Chương 1: Mệnh đề)', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_type',
            field=models.CharField(choices=[('CHAPTER', 'Chương'), ('THEME', 'Chủ đề')], default='CHAPTER', help_text='CHAPTER = Chương (Toán/Lý/Hóa), THEME = Chủ đề (Lý mới/GDCD/LS/ĐL)', max_length=10),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(help_text='Tên hiển thị tổng hợp (= ten_chuong hoặc ten_chu_de, tùy chapter_type)', max_length=512),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_number',
            field=models.CharField(blank=True, help_text="Số bài (ví dụ: '1', '2', '3') - lấy từ mục lục, không tách từ tên bài", max_length=20, null=True),
        ),
    ]
