# Generated by Django 4.2.30 on 2026-04-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_grade_level_customuser_last_quest_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='completed_quests',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rank',
            field=models.CharField(default='Tập Sự', max_length=50),
        ),
    ]
