# Generated by Django 4.2.29 on 2026-04-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_completed_quests_alter_customuser_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ai_preferences',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_global_history_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
