# Generated by Django 4.2.29 on 2026-04-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_ai_preferences_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='streak',
            new_name='current_streak',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='points',
            new_name='total_xp',
        ),
        migrations.AddField(
            model_name='customuser',
            name='gems',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='max_streak',
            field=models.IntegerField(default=0),
        ),
    ]
