# Generated by Django 4.2.30 on 2026-04-22 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_avatar_url_customuser_full_name'),
        ('users', '0006_rename_streak_customuser_current_streak_and_more'),
    ]

    operations = [
    ]
