# Generated by Django 4.2.29 on 2026-05-01 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_question_chapter_title_question_explanation_and_more'),
        ('curriculum', '0001_initial'),
        ('subjects', '0008_subject_page_offset'),
        ('users', '0007_merge_20260422_0648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningpath',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='learningpath',
            name='ai_feedback',
            field=models.TextField(blank=True, default='', help_text='Nhận xét cá nhân hóa từ Gemini'),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='pre_test_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Điểm pre-test (%) dùng để tạo lộ trình', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Đang học'), ('COMPLETED', 'Đã hoàn thành'), ('PENDING', 'Chờ AI phân tích')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='strategy',
            field=models.CharField(choices=[('foundation', 'Nền tảng'), ('standard', 'Tiêu chuẩn'), ('advanced', 'Nâng cao')], default='standard', help_text='Chiến lược học do AI chọn', max_length=20),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to='subjects.subject'),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='learningpath',
            unique_together={('user', 'subject')},
        ),
        migrations.CreateModel(
            name='LearningPathItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('LESSON', 'Bài học'), ('QUIZ', 'Kiểm tra')], max_length=10)),
                ('order_num', models.IntegerField(default=0)),
                ('is_unlocked', models.BooleanField(default=False)),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='users.learningpath')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='path_items', to='curriculum.lesson')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='path_items', to='quiz.quiz')),
            ],
            options={
                'ordering': ['order_num'],
            },
        ),
        migrations.RemoveField(
            model_name='learningpath',
            name='current_chapter',
        ),
        migrations.RemoveField(
            model_name='learningpath',
            name='progress_percentage',
        ),
        migrations.CreateModel(
            name='LearningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Chưa bắt đầu'), ('IN_PROGRESS', 'Đang học'), ('COMPLETED', 'Hoàn thành')], default='NOT_STARTED', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Điểm quiz nếu item là QUIZ', max_digits=5, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('learning_path_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='users.learningpathitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'learning_path_item')},
            },
        ),
    ]
