# Generated by Django 4.2.29 on 2026-05-04 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_topic'),
        ('users', '0008_alter_learningpath_options_learningpath_ai_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpathitem',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='Mục nhỏ cụ thể cần học', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='path_items', to='curriculum.topic'),
        ),
        migrations.AlterField(
            model_name='learningpathitem',
            name='item_type',
            field=models.CharField(choices=[('LESSON', 'Bài học lớn'), ('TOPIC', 'Mục kiến thức'), ('QUIZ', 'Kiểm tra')], max_length=10),
        ),
    ]
