# Generated by Django 4.2.29 on 2026-05-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_learningpathitem_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningprogress',
            name='error_tags',
            field=models.JSONField(blank=True, default=list, help_text="Lưu các tag lỗi sai để AI phân tích nguyên nhân (ví dụ: 'ẩu', 'hổng-kiến-thức')"),
        ),
        migrations.AddField(
            model_name='learningprogress',
            name='mastery_level',
            field=models.CharField(choices=[('RED', 'Yếu'), ('YELLOW', 'Cần cố gắng'), ('GREEN', 'Thành thạo')], default='RED', help_text='Mức độ thông thạo theo hệ thống Đèn giao thông', max_length=20),
        ),
    ]
