# Generated by Django 4.2.30 on 2026-05-06 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_topic'),
        ('users', '0010_learningprogress_error_tags_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='learningpath',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to='curriculum.chapter'),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='pre_test_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Điểm đánh giá đầu vào (%)', max_digits=5, null=True),
        ),
    ]
