# Generated by Django 4.2.30 on 2026-05-10 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_add_bio_dob_to_user'),
        ('users', '0011_add_chapter_to_learningpath'),
    ]

    operations = [
    ]
