# Generated by Django 4.2.30 on 2026-05-13 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0009_subjectstats'),
        ('curriculum', '0003_contentchunk'),
        ('users', '0012_merge_20260510_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('teacher', 'Teacher')], default='student', max_length=10),
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.IntegerField(default=0)),
                ('lessons_completed', models.IntegerField(default=0)),
                ('perfect_quizzes', models.IntegerField(default=0)),
                ('pvp_wins', models.IntegerField(default=0)),
                ('pvp_games_played', models.IntegerField(default=0)),
                ('max_win_streak', models.IntegerField(default=0)),
                ('tower_floor_reached', models.IntegerField(default=0)),
                ('chat_messages_count', models.IntegerField(default=0)),
                ('ai_explanations_requested', models.IntegerField(default=0)),
                ('gems_earned', models.IntegerField(default=0)),
                ('login_streak', models.IntegerField(default=0)),
                ('last_login_date', models.DateField(blank=True, null=True)),
                ('total_sessions', models.IntegerField(default=0)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('current_chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.chapter')),
                ('current_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
