# Generated by Django 4.2.30 on 2026-05-10 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_merge_20260510_0838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='user',
        ),
        migrations.AlterModelTable(
            name='learningpath',
            table='user_learning_path',
        ),
        migrations.AlterModelTable(
            name='learningpathitem',
            table='user_learning_path_item',
        ),
        migrations.AlterModelTable(
            name='learningprogress',
            table='user_learning_progress',
        ),
    ]
