# Generated by Django 4.2.30 on 2026-05-10 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_standardize_db_table_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='completed_quests',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rank',
            field=models.CharField(default='Beginner', max_length=50),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='users',
        ),
        migrations.AlterModelTable(
            name='learningpath',
            table='learning_paths',
        ),
        migrations.AlterModelTable(
            name='learningpathitem',
            table='learning_path_items',
        ),
        migrations.AlterModelTable(
            name='learningprogress',
            table='learning_progress',
        ),
        migrations.CreateModel(
            name='UserStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.IntegerField(default=0)),
                ('lessons_completed', models.IntegerField(default=0)),
                ('perfect_quizzes', models.IntegerField(default=0)),
                ('pvp_wins', models.IntegerField(default=0)),
                ('pvp_games_played', models.IntegerField(default=0)),
                ('max_win_streak', models.IntegerField(default=0)),
                ('tower_floor_reached', models.IntegerField(default=0)),
                ('chat_messages_count', models.IntegerField(default=0)),
                ('ai_explanations_requested', models.IntegerField(default=0)),
                ('gems_earned', models.IntegerField(default=0)),
                ('login_streak', models.IntegerField(default=0)),
                ('last_login_date', models.DateField(blank=True, null=True)),
                ('total_sessions', models.IntegerField(default=0)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('current_subject_id', models.BigIntegerField(blank=True, null=True)),
                ('current_chapter_id', models.BigIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_stats',
            },
        ),
    ]
