# Generated by Django 4.2.30 on 2026-05-14 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_customuser_role_userstats'),
        ('users', '0014_alter_customuser_completed_quests_and_more'),
    ]

    operations = [
    ]
