# Generated by Django 4.2.30 on 2026-05-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_merge_20260514_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpath',
            name='post_test_ai_feedback',
            field=models.TextField(blank=True, default='', help_text='Nhận xét AI so sánh trước/sau khi học'),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='post_test_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Điểm bài kiểm tra cuối chương (%)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User')], default='USER', max_length=10),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Đang học'), ('COMPLETED', 'Đã hoàn thành'), ('PENDING', 'Chờ AI phân tích'), ('LOCKED', 'Chưa mở khóa')], default='PENDING', max_length=20),
        ),
        migrations.DeleteModel(
            name='UserStats',
        ),
    ]
