# Generated by Django 4.2.29 on 2026-03-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_subjectdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectdocument',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Upload original PDF textbook', null=True, upload_to='books/pdfs/'),
        ),
        migrations.AlterField(
            model_name='subjectdocument',
            name='content',
            field=models.TextField(blank=True, help_text='Extracted text content from the textbook', null=True),
        ),
    ]
