# Generated by Django 4.2.29 on 2026-03-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_subjectdocument_pdf_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='grade_level',
            field=models.IntegerField(choices=[(10, 'Lớp 10'), (11, 'Lớp 11'), (12, 'Lớp 12')], default=12),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'grade_level')},
        ),
    ]
