# Generated by Django 4.2.29 on 2026-04-07 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0006_subjectchapter_subjectlesson_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectlesson',
            name='chapter',
        ),
        migrations.DeleteModel(
            name='SubjectChapter',
        ),
        migrations.DeleteModel(
            name='SubjectLesson',
        ),
    ]
