# Generated by Django 4.2.29 on 2026-04-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_remove_subjectlesson_chapter_delete_subjectchapter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='page_offset',
            field=models.IntegerField(default=0, help_text='Số trang cần bù để khớp trang in và trang PDF'),
        ),
    ]
