# Generated by Django 4.2.30 on 2026-05-13 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0008_subject_page_offset'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.IntegerField(default=0)),
                ('active_students', models.IntegerField(default=0)),
                ('chat_sessions', models.IntegerField(default=0)),
                ('learning_paths_created', models.IntegerField(default=0)),
                ('total_sessions', models.IntegerField(default=0)),
                ('trend_last_7days', models.CharField(blank=True, max_length=30, null=True)),
                ('last_calculated_at', models.DateTimeField(blank=True, null=True)),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='subjects.subject')),
            ],
        ),
    ]
