# Generated by Django 4.2.30 on 2026-05-10 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0008_subject_page_offset'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subject',
            table='subject',
        ),
        migrations.AlterModelTable(
            name='subjectdocument',
            table='subject_document',
        ),
    ]
