# Generated by Django 4.2.30 on 2026-05-14 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0009_subjectstats'),
        ('subjects', '0010_alter_subject_table_alter_subjectdocument_table_and_more'),
    ]

    operations = [
    ]
