# Generated by Django 4.2.29 on 2026-04-07 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_remove_subjectlesson_chapter_delete_subjectchapter_and_more'),
        ('quiz', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='passing_score',
            field=models.IntegerField(default=70, help_text='Điểm sàn để vượt qua (%)'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('PRE_TEST', 'Pre-Test (Đầu vào)'), ('POST_TEST', 'Post-Test (Vượt ải)'), ('PRACTICE', 'Practice (Luyện tập AI)')], default='PRACTICE', max_length=20),
        ),
        migrations.AddField(
            model_name='quiz',
            name='related_document',
            field=models.ForeignKey(blank=True, help_text='Tài liệu/trang sách liên kết (Dành cho Post-test và Practice)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='subjects.subjectdocument'),
        ),
    ]
