# Generated by Django 4.2.29 on 2026-05-01 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quiz_passing_score_quiz_quiz_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='chapter_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Giải thích đáp án đúng', null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='chapter_coverage',
            field=models.JSONField(blank=True, default=list, help_text='Danh sách chapter_title mà quiz này bao phủ'),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='answers_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='wrong_chapters',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Trắc nghiệm 1 đáp án'), ('TRUE_FALSE', 'Đúng/Sai')], default='MCQ', max_length=50),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('order_num', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.question')),
            ],
            options={
                'ordering': ['order_num'],
            },
        ),
    ]
