# Generated by Django 4.2.29 on 2026-05-04 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_topic'),
        ('quiz', '0004_question_chapter_title_question_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty_level',
            field=models.IntegerField(choices=[(1, 'Nhận biết (Dễ)'), (2, 'Thông hiểu (Trung bình)'), (3, 'Vận dụng (Khá)'), (4, 'Vận dụng cao (Khó)'), (5, 'Cực khó (Nâng cao)')], default=1, help_text='Mức độ từ 1 (Dễ) đến 5 (Khó)'),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='Liên kết câu hỏi với mục kiến thức cụ thể', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='curriculum.topic'),
        ),
    ]
