# Generated by Django 4.2.30 on 2026-05-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_question_difficulty_level_question_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('PRE_TEST', 'Pre-Test (Đầu vào)'), ('POST_TEST', 'Post-Test (Vượt ải)'), ('PRACTICE', 'Practice (Luyện tập AI)'), ('CHAPTER_TEST', 'Chapter Test (Đánh giá đầu vào theo Chương)')], default='PRACTICE', max_length=20),
        ),
    ]
