# Generated by Django 4.2.29 on 2026-05-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_add_chapter_test_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='battle_eligible',
            field=models.BooleanField(default=False, help_text='Câu hỏi đủ điều kiện sử dụng trong Đấu trường'),
        ),
        migrations.AddField(
            model_name='question',
            name='bloom_level',
            field=models.IntegerField(default=1, help_text='Cấp độ Bloom (1-6)'),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty_score',
            field=models.FloatField(default=1.0, help_text='Độ khó thực tế (0.0 - 10.0)'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_boss_question',
            field=models.BooleanField(default=False, help_text='Câu hỏi chốt hạ để vượt tầng tháp'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_input_test',
            field=models.BooleanField(default=False, help_text='Sử dụng cho bài kiểm tra đầu vào/phân loại'),
        ),
        migrations.AddField(
            model_name='question',
            name='verified_answer',
            field=models.BooleanField(default=False, help_text='Câu hỏi đã được xác minh tính đúng đắn (qua thực tế làm bài)'),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='bloom_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty_level',
            field=models.IntegerField(choices=[(1, 'Nhận biết (Remember)'), (2, 'Thông hiểu (Understand)'), (3, 'Vận dụng (Apply)'), (4, 'Phân tích (Analyze)'), (5, 'Đánh giá (Evaluate)'), (6, 'Sáng tạo (Create)')], default=1, help_text='Cấp độ nhận thức theo thang đo Bloom (1-6)'),
        ),
    ]
