# Generated by Django 4.2.30 on 2026-05-10 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_question_battle_eligible_question_bloom_level_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='answer',
            table='quiz_answer',
        ),
        migrations.AlterModelTable(
            name='question',
            table='quiz_question',
        ),
        migrations.AlterModelTable(
            name='quiz',
            table='quiz',
        ),
        migrations.AlterModelTable(
            name='quizsubmission',
            table='quiz_submission',
        ),
    ]
