# Generated by Django 4.2.30 on 2026-05-10 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_standardize_db_table_names'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='answer',
            table='answers',
        ),
        migrations.AlterModelTable(
            name='question',
            table='questions',
        ),
        migrations.AlterModelTable(
            name='quiz',
            table='quizzes',
        ),
        migrations.AlterModelTable(
            name='quizsubmission',
            table='quiz_submissions',
        ),
    ]
