# Generated by Django 4.2.30 on 2026-05-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_answer_table_alter_question_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='chapter_type',
            field=models.CharField(blank=True, choices=[('CHAPTER', 'Chương'), ('THEME', 'Chủ đề')], help_text='Phân loại: Chương (Tự nhiên) hoặc Chủ đề (Xã hội)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='part_title',
            field=models.CharField(blank=True, help_text='Tên Phần (Ví dụ: Phần 1)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='chapter_title',
            field=models.CharField(blank=True, help_text='Tên Chương hoặc Tên Chủ đề', max_length=255, null=True),
        ),
    ]
