# Generated by Django 4.2.29 on 2026-05-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_question_chapter_type_question_part_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='lesson_number',
            field=models.CharField(blank=True, help_text='Số thứ tự bài học (ví dụ: Bài 1)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='lesson_title',
            field=models.CharField(blank=True, help_text='Tên bài học', max_length=255, null=True),
        ),
    ]
