# Generated by Django 4.2.29 on 2026-05-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_question_lesson_number_question_lesson_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='grade_level',
            field=models.IntegerField(blank=True, help_text='Khối lớp (10, 11, 12)', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='subject_name',
            field=models.CharField(blank=True, help_text='Tên môn học', max_length=100, null=True),
        ),
    ]
