# Generated by Django 4.2.29 on 2026-04-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_storeitem_userinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyquest',
            name='floor_level',
            field=models.IntegerField(default=1),
        ),
    ]
