# Generated by Django 4.2.30 on 2026-05-04 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamification', '0003_dailyquest_floor_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='badge_type',
        ),
        migrations.AddField(
            model_name='badge',
            name='category',
            field=models.CharField(choices=[('LEARNING', 'Học tập'), ('ARENA', 'Đấu trường'), ('SOCIAL', 'Xã hội'), ('CONSISTENCY', 'Chuyên cần'), ('AI', 'Trí tuệ nhân tạo')], default='LEARNING', max_length=20),
        ),
        migrations.AddField(
            model_name='badge',
            name='code',
            field=models.CharField(default='GENERIC_BADGE', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='criteria_type',
            field=models.CharField(default='generic', help_text='Ví dụ: lessons_completed, pvp_wins, chat_count', max_length=50),
        ),
        migrations.CreateModel(
            name='UserStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessons_completed', models.IntegerField(default=0)),
                ('perfect_quizzes', models.IntegerField(default=0)),
                ('total_xp', models.IntegerField(default=0)),
                ('pvp_wins', models.IntegerField(default=0)),
                ('pvp_games_played', models.IntegerField(default=0)),
                ('max_win_streak', models.IntegerField(default=0)),
                ('tower_floor_reached', models.IntegerField(default=0)),
                ('chat_messages_count', models.IntegerField(default=0)),
                ('ai_explanations_requested', models.IntegerField(default=0)),
                ('gems_earned', models.IntegerField(default=0)),
                ('login_streak', models.IntegerField(default=0)),
                ('last_login_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
