# Generated by Django 4.2.30 on 2026-05-10 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamification', '0005_standardize_db_table_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Inventories',
                'db_table': 'inventories',
            },
        ),
        migrations.AlterModelTable(
            name='badge',
            table='badges',
        ),
        migrations.AlterModelTable(
            name='dailyquest',
            table='daily_quests',
        ),
        migrations.AlterModelTable(
            name='storeitem',
            table='store_items',
        ),
        migrations.AlterModelTable(
            name='userbadge',
            table='user_badges',
        ),
        migrations.DeleteModel(
            name='UserInventory',
        ),
        migrations.AddField(
            model_name='inventory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.storeitem'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL),
        ),
    ]
