# Generated by Django 4.2.29 on 2026-05-14 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0006_inventory_remove_userstat_user_alter_badge_table_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyQuest',
        ),
    ]
