# Generated by Django 4.2.29 on 2026-04-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_message_subject_chatthread_message_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='source_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
