# Generated by Django 4.2.30 on 2026-05-10 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_message_source_metadata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatthread',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelTable(
            name='chatthread',
            table='chat_thread',
        ),
        migrations.AlterModelTable(
            name='message',
            table='chat_message',
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='chat/images/%Y/%m/')),
                ('file_url', models.TextField(blank=True, help_text='URL tuyệt đối nếu lưu trên cloud')),
                ('attachment_type', models.CharField(choices=[('image', 'Hình ảnh'), ('file', 'Tệp đính kèm')], default='image', max_length=10)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(blank=True, help_text='Tin nhắn chứa tệp đính kèm này (null nếu upload trước khi gửi)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.message')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.chatthread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_attachment',
                'ordering': ['-created_at'],
            },
        ),
    ]
