# Generated by Django 4.2.30 on 2026-05-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_upload_alter_chatthread_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='chat_type',
            field=models.CharField(choices=[('qa', 'Hỏi đáp'), ('learning_path', 'Tạo lộ trình')], default='qa', max_length=20),
        ),
    ]
