# Generated by Django 4.2.30 on 2026-05-10 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chatthread_chat_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatthread',
            name='chat_type',
        ),
    ]
