# Generated by Django 4.2.30 on 2026-05-14 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_upload'),
        ('chat', '0008_remove_chatthread_chat_type'),
    ]

    operations = [
    ]
