# Generated by Django 4.2.29 on 2026-04-19 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.IntegerField(default=12)),
                ('question_ids', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Chờ đối thủ'), ('in_progress', 'Đang diễn ra'), ('completed', 'Đã kết thúc'), ('expired', 'Hết hạn'), ('cancelled', 'Đã hủy')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_challenger', to=settings.AUTH_USER_MODEL)),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_opponent', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battles_won', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trận Đấu',
                'verbose_name_plural': 'Trận Đấu',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BattleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('correct_count', models.IntegerField(default=0)),
                ('total_time', models.FloatField(default=0.0)),
                ('answer_log', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='battle.battle')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kết Quả Trận Đấu',
                'verbose_name_plural': 'Kết Quả Trận Đấu',
                'unique_together': {('battle', 'player')},
            },
        ),
    ]
