# Generated by Django 4.2.29 on 2026-05-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='subject',
            field=models.CharField(default='Toán học', max_length=100),
        ),
    ]
