# Generated by Django 4.2.30 on 2026-05-10 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0002_battle_subject'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='battle',
            table='battle',
        ),
        migrations.AlterModelTable(
            name='battleresult',
            table='battle_result',
        ),
    ]
