# Generated by Django 4.2.30 on 2026-05-10 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0003_standardize_db_table_names'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='battle',
            table='battles',
        ),
        migrations.AlterModelTable(
            name='battleresult',
            table='battle_results',
        ),
    ]
